# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jaylen\Desktop\glass\windowtest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(390, 463)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 10, 171, 41))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(60, 60, 281, 391))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(270, 300, 47, 13))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">Glass Estimation</span></p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Doors:"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "Framing:"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "Glass:"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "Others:"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "Framing:"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "Special:"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "Labor:"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "35 % MU"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "Sub Totals:"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "Grand Total:"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Form", "Stand Alone:"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Form", "Final Total:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Option #1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Option #2"))
        self.label_2.setText(_translate("Form", "35 % MU"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
